name: cachix
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: cachix
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v18
    - uses: cachix/cachix-action@v12
      with:
        name: pylgos-godot-custom
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -L .#godot-camera-branch
